[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run start"
  framework = "#custom"
  functions = "functions"
  publish = "dist"
  targetPort = 3000

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/api/read"
  to = "/.netlify/functions/read"
  status = 200
  force = true

[[redirects]]
  from = "/api/read-all"
  to = "/.netlify/functions/read-all"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
